# Generated by Django 4.1.1 on 2022-09-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('ownerID', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PictureFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_folder_name', models.CharField(max_length=100)),
                ('piture_folder_password', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_share_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='PictureComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('pictureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_share_app.allpictures')),
            ],
        ),
        migrations.AddField(
            model_name='allpictures',
            name='picture_folderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_share_app.picturefolder'),
        ),
    ]
