# Generated by Django 4.1.1 on 2022-09-15 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='all_pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='picture_folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_folder_name', models.CharField(max_length=100, unique=True)),
                ('piture_folder_password', models.CharField(max_length=100)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='picture_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('pictureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_share_app.all_pictures')),
            ],
        ),
        migrations.AddField(
            model_name='all_pictures',
            name='picture_folderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_share_app.picture_folder'),
        ),
    ]
