# Generated by Django 4.1.1 on 2022-09-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_share_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_folder',
            name='picture_folder_name',
            field=models.CharField(max_length=100),
        ),
    ]
