# Generated by Django 4.1.1 on 2022-09-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_share_app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_folder',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_share_app.user'),
        ),
    ]
