# Generated by Django 4.1.1 on 2022-09-18 10:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_share_app', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='all_pictures',
            new_name='AllPictures',
        ),
        migrations.RenameModel(
            old_name='picture_comment',
            new_name='PictureComment',
        ),
        migrations.RenameModel(
            old_name='picture_folder',
            new_name='PictureFolder',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
