# Generated by Django 4.1.1 on 2022-09-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_share_app', '0002_alter_picture_folder_picture_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_folder',
            name='piture_folder_password',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
